<Project>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AvaloniaVersion>12.0.2</AvaloniaVersion>

    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DefaultCSharp" Version="14.0.2" PrivateAssets="all" />
    <PackageReference Include="Polyfill" Version="10.3.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
