<Project>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AvaloniaVersion>12.0.0</AvaloniaVersion>

    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DefaultCSharp" Version="14.0.2" PrivateAssets="all" />
    <PackageReference Include="Polyfill" Version="10.2.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
